package com.surwing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bed service. Represents a row in the &quot;M_Bed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.BedModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.BedImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see Bed
 * @see com.surwing.model.impl.BedImpl
 * @see com.surwing.model.impl.BedModelImpl
 * @generated
 */
public interface BedModel extends BaseModel<Bed> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a bed model instance should use the {@link Bed} interface instead.
     */

    /**
     * Returns the primary key of this bed.
     *
     * @return the primary key of this bed
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this bed.
     *
     * @param primaryKey the primary key of this bed
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the bed ID of this bed.
     *
     * @return the bed ID of this bed
     */
    public long getBedId();

    /**
     * Sets the bed ID of this bed.
     *
     * @param bedId the bed ID of this bed
     */
    public void setBedId(long bedId);

    /**
     * Returns the company ID of this bed.
     *
     * @return the company ID of this bed
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this bed.
     *
     * @param companyId the company ID of this bed
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this bed.
     *
     * @return the group ID of this bed
     */
    public long getGroupId();

    /**
     * Sets the group ID of this bed.
     *
     * @param groupId the group ID of this bed
     */
    public void setGroupId(long groupId);

    /**
     * Returns the location ID of this bed.
     *
     * @return the location ID of this bed
     */
    public long getLocationId();

    /**
     * Sets the location ID of this bed.
     *
     * @param locationId the location ID of this bed
     */
    public void setLocationId(long locationId);

    /**
     * Returns the bed no of this bed.
     *
     * @return the bed no of this bed
     */
    @AutoEscape
    public String getBedNo();

    /**
     * Sets the bed no of this bed.
     *
     * @param bedNo the bed no of this bed
     */
    public void setBedNo(String bedNo);

    /**
     * Returns the alias of this bed.
     *
     * @return the alias of this bed
     */
    @AutoEscape
    public String getAlias();

    /**
     * Sets the alias of this bed.
     *
     * @param alias the alias of this bed
     */
    public void setAlias(String alias);

    /**
     * Returns the patient ID of this bed.
     *
     * @return the patient ID of this bed
     */
    public long getPatientId();

    /**
     * Sets the patient ID of this bed.
     *
     * @param patientId the patient ID of this bed
     */
    public void setPatientId(long patientId);

    /**
     * Returns the create date of this bed.
     *
     * @return the create date of this bed
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this bed.
     *
     * @param createDate the create date of this bed
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this bed.
     *
     * @return the modified date of this bed
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this bed.
     *
     * @param modifiedDate the modified date of this bed
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.Bed bed);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.Bed> toCacheModel();

    @Override
    public com.surwing.model.Bed toEscapedModel();

    @Override
    public com.surwing.model.Bed toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
