package com.surwing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Node service. Represents a row in the &quot;M_Node&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.NodeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.NodeImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see Node
 * @see com.surwing.model.impl.NodeImpl
 * @see com.surwing.model.impl.NodeModelImpl
 * @generated
 */
public interface NodeModel extends BaseModel<Node> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a node model instance should use the {@link Node} interface instead.
     */

    /**
     * Returns the primary key of this node.
     *
     * @return the primary key of this node
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this node.
     *
     * @param primaryKey the primary key of this node
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the node ID of this node.
     *
     * @return the node ID of this node
     */
    public long getNodeId();

    /**
     * Sets the node ID of this node.
     *
     * @param nodeId the node ID of this node
     */
    public void setNodeId(long nodeId);

    /**
     * Returns the company ID of this node.
     *
     * @return the company ID of this node
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this node.
     *
     * @param companyId the company ID of this node
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this node.
     *
     * @return the group ID of this node
     */
    public long getGroupId();

    /**
     * Sets the group ID of this node.
     *
     * @param groupId the group ID of this node
     */
    public void setGroupId(long groupId);

    /**
     * Returns the node no of this node.
     *
     * @return the node no of this node
     */
    @AutoEscape
    public String getNodeNo();

    /**
     * Sets the node no of this node.
     *
     * @param nodeNo the node no of this node
     */
    public void setNodeNo(String nodeNo);

    /**
     * Returns the location ID of this node.
     *
     * @return the location ID of this node
     */
    public long getLocationId();

    /**
     * Sets the location ID of this node.
     *
     * @param locationId the location ID of this node
     */
    public void setLocationId(long locationId);

    /**
     * Returns the node type of this node.
     *
     * @return the node type of this node
     */
    public int getNodeType();

    /**
     * Sets the node type of this node.
     *
     * @param nodeType the node type of this node
     */
    public void setNodeType(int nodeType);

    /**
     * Returns the ip of this node.
     *
     * @return the ip of this node
     */
    @AutoEscape
    public String getIp();

    /**
     * Sets the ip of this node.
     *
     * @param ip the ip of this node
     */
    public void setIp(String ip);

    /**
     * Returns the last received time of this node.
     *
     * @return the last received time of this node
     */
    public Date getLastReceivedTime();

    /**
     * Sets the last received time of this node.
     *
     * @param lastReceivedTime the last received time of this node
     */
    public void setLastReceivedTime(Date lastReceivedTime);

    /**
     * Returns the last transmit time of this node.
     *
     * @return the last transmit time of this node
     */
    public Date getLastTransmitTime();

    /**
     * Sets the last transmit time of this node.
     *
     * @param lastTransmitTime the last transmit time of this node
     */
    public void setLastTransmitTime(Date lastTransmitTime);

    /**
     * Returns the status of this node.
     *
     * @return the status of this node
     */
    public int getStatus();

    /**
     * Sets the status of this node.
     *
     * @param status the status of this node
     */
    public void setStatus(int status);

    /**
     * Returns the create date of this node.
     *
     * @return the create date of this node
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this node.
     *
     * @param createDate the create date of this node
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this node.
     *
     * @return the modified date of this node
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this node.
     *
     * @param modifiedDate the modified date of this node
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.Node node);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.Node> toCacheModel();

    @Override
    public com.surwing.model.Node toEscapedModel();

    @Override
    public com.surwing.model.Node toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
