package com.surwing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.math.BigDecimal;

import java.util.Date;

/**
 * The base model interface for the Patient service. Represents a row in the &quot;M_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.PatientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.PatientImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see Patient
 * @see com.surwing.model.impl.PatientImpl
 * @see com.surwing.model.impl.PatientModelImpl
 * @generated
 */
public interface PatientModel extends BaseModel<Patient> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link Patient} interface instead.
     */

    /**
     * Returns the primary key of this patient.
     *
     * @return the primary key of this patient
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this patient.
     *
     * @param primaryKey the primary key of this patient
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the patient ID of this patient.
     *
     * @return the patient ID of this patient
     */
    public long getPatientId();

    /**
     * Sets the patient ID of this patient.
     *
     * @param patientId the patient ID of this patient
     */
    public void setPatientId(long patientId);

    /**
     * Returns the company ID of this patient.
     *
     * @return the company ID of this patient
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this patient.
     *
     * @param companyId the company ID of this patient
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this patient.
     *
     * @return the group ID of this patient
     */
    public long getGroupId();

    /**
     * Sets the group ID of this patient.
     *
     * @param groupId the group ID of this patient
     */
    public void setGroupId(long groupId);

    /**
     * Returns the mrn of this patient.
     *
     * @return the mrn of this patient
     */
    @AutoEscape
    public String getMrn();

    /**
     * Sets the mrn of this patient.
     *
     * @param mrn the mrn of this patient
     */
    public void setMrn(String mrn);

    /**
     * Returns the name of this patient.
     *
     * @return the name of this patient
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this patient.
     *
     * @param name the name of this patient
     */
    public void setName(String name);

    /**
     * Returns the location ID of this patient.
     *
     * @return the location ID of this patient
     */
    public long getLocationId();

    /**
     * Sets the location ID of this patient.
     *
     * @param locationId the location ID of this patient
     */
    public void setLocationId(long locationId);

    /**
     * Returns the bed ID of this patient.
     *
     * @return the bed ID of this patient
     */
    public long getBedId();

    /**
     * Sets the bed ID of this patient.
     *
     * @param bedId the bed ID of this patient
     */
    public void setBedId(long bedId);

    /**
     * Returns the gender of this patient.
     *
     * @return the gender of this patient
     */
    public int getGender();

    /**
     * Sets the gender of this patient.
     *
     * @param gender the gender of this patient
     */
    public void setGender(int gender);

    /**
     * Returns the birthday of this patient.
     *
     * @return the birthday of this patient
     */
    public Date getBirthday();

    /**
     * Sets the birthday of this patient.
     *
     * @param birthday the birthday of this patient
     */
    public void setBirthday(Date birthday);

    /**
     * Returns the min temperature of this patient.
     *
     * @return the min temperature of this patient
     */
    public BigDecimal getMinTemperature();

    /**
     * Sets the min temperature of this patient.
     *
     * @param minTemperature the min temperature of this patient
     */
    public void setMinTemperature(BigDecimal minTemperature);

    /**
     * Returns the max temperature of this patient.
     *
     * @return the max temperature of this patient
     */
    public BigDecimal getMaxTemperature();

    /**
     * Sets the max temperature of this patient.
     *
     * @param maxTemperature the max temperature of this patient
     */
    public void setMaxTemperature(BigDecimal maxTemperature);

    /**
     * Returns the tag no of this patient.
     *
     * @return the tag no of this patient
     */
    @AutoEscape
    public String getTagNo();

    /**
     * Sets the tag no of this patient.
     *
     * @param tagNo the tag no of this patient
     */
    public void setTagNo(String tagNo);

    /**
     * Returns the temperature of this patient.
     *
     * @return the temperature of this patient
     */
    public BigDecimal getTemperature();

    /**
     * Sets the temperature of this patient.
     *
     * @param temperature the temperature of this patient
     */
    public void setTemperature(BigDecimal temperature);

    /**
     * Returns the latest date of this patient.
     *
     * @return the latest date of this patient
     */
    public Date getLatestDate();

    /**
     * Sets the latest date of this patient.
     *
     * @param latestDate the latest date of this patient
     */
    public void setLatestDate(Date latestDate);

    /**
     * Returns the temperature in8h of this patient.
     *
     * @return the temperature in8h of this patient
     */
    public BigDecimal getTemperatureIn8h();

    /**
     * Sets the temperature in8h of this patient.
     *
     * @param temperatureIn8h the temperature in8h of this patient
     */
    public void setTemperatureIn8h(BigDecimal temperatureIn8h);

    /**
     * Returns the highest date of this patient.
     *
     * @return the highest date of this patient
     */
    public Date getHighestDate();

    /**
     * Sets the highest date of this patient.
     *
     * @param highestDate the highest date of this patient
     */
    public void setHighestDate(Date highestDate);

    /**
     * Returns the febrile of this patient.
     *
     * @return the febrile of this patient
     */
    public boolean getFebrile();

    /**
     * Returns <code>true</code> if this patient is febrile.
     *
     * @return <code>true</code> if this patient is febrile; <code>false</code> otherwise
     */
    public boolean isFebrile();

    /**
     * Sets whether this patient is febrile.
     *
     * @param febrile the febrile of this patient
     */
    public void setFebrile(boolean febrile);

    /**
     * Returns the alarm level of this patient.
     *
     * @return the alarm level of this patient
     */
    public BigDecimal getAlarmLevel();

    /**
     * Sets the alarm level of this patient.
     *
     * @param alarmLevel the alarm level of this patient
     */
    public void setAlarmLevel(BigDecimal alarmLevel);

    /**
     * Returns the discharge of this patient.
     *
     * @return the discharge of this patient
     */
    public boolean getDischarge();

    /**
     * Returns <code>true</code> if this patient is discharge.
     *
     * @return <code>true</code> if this patient is discharge; <code>false</code> otherwise
     */
    public boolean isDischarge();

    /**
     * Sets whether this patient is discharge.
     *
     * @param discharge the discharge of this patient
     */
    public void setDischarge(boolean discharge);

    /**
     * Returns the deleted of this patient.
     *
     * @return the deleted of this patient
     */
    public boolean getDeleted();

    /**
     * Returns <code>true</code> if this patient is deleted.
     *
     * @return <code>true</code> if this patient is deleted; <code>false</code> otherwise
     */
    public boolean isDeleted();

    /**
     * Sets whether this patient is deleted.
     *
     * @param deleted the deleted of this patient
     */
    public void setDeleted(boolean deleted);

    /**
     * Returns the create date of this patient.
     *
     * @return the create date of this patient
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this patient.
     *
     * @param createDate the create date of this patient
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this patient.
     *
     * @return the modified date of this patient
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this patient.
     *
     * @param modifiedDate the modified date of this patient
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.Patient patient);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.Patient> toCacheModel();

    @Override
    public com.surwing.model.Patient toEscapedModel();

    @Override
    public com.surwing.model.Patient toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
