package com.surwing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the SystemParameter service. Represents a row in the &quot;M_SystemParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.SystemParameterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.SystemParameterImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see SystemParameter
 * @see com.surwing.model.impl.SystemParameterImpl
 * @see com.surwing.model.impl.SystemParameterModelImpl
 * @generated
 */
public interface SystemParameterModel extends BaseModel<SystemParameter> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a system parameter model instance should use the {@link SystemParameter} interface instead.
     */

    /**
     * Returns the primary key of this system parameter.
     *
     * @return the primary key of this system parameter
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this system parameter.
     *
     * @param primaryKey the primary key of this system parameter
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the system parameter ID of this system parameter.
     *
     * @return the system parameter ID of this system parameter
     */
    public long getSystemParameterId();

    /**
     * Sets the system parameter ID of this system parameter.
     *
     * @param systemParameterId the system parameter ID of this system parameter
     */
    public void setSystemParameterId(long systemParameterId);

    /**
     * Returns the location ID of this system parameter.
     *
     * @return the location ID of this system parameter
     */
    public long getLocationId();

    /**
     * Sets the location ID of this system parameter.
     *
     * @param locationId the location ID of this system parameter
     */
    public void setLocationId(long locationId);

    /**
     * Returns the key of this system parameter.
     *
     * @return the key of this system parameter
     */
    @AutoEscape
    public String getKey();

    /**
     * Sets the key of this system parameter.
     *
     * @param key the key of this system parameter
     */
    public void setKey(String key);

    /**
     * Returns the value of this system parameter.
     *
     * @return the value of this system parameter
     */
    @AutoEscape
    public String getValue();

    /**
     * Sets the value of this system parameter.
     *
     * @param value the value of this system parameter
     */
    public void setValue(String value);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.SystemParameter systemParameter);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.SystemParameter> toCacheModel();

    @Override
    public com.surwing.model.SystemParameter toEscapedModel();

    @Override
    public com.surwing.model.SystemParameter toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
