package com.surwing.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tag service. Represents a row in the &quot;M_Tag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.TagModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.TagImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see Tag
 * @see com.surwing.model.impl.TagImpl
 * @see com.surwing.model.impl.TagModelImpl
 * @generated
 */
public interface TagModel extends BaseModel<Tag> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a tag model instance should use the {@link Tag} interface instead.
     */

    /**
     * Returns the primary key of this tag.
     *
     * @return the primary key of this tag
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this tag.
     *
     * @param primaryKey the primary key of this tag
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the tag ID of this tag.
     *
     * @return the tag ID of this tag
     */
    public long getTagId();

    /**
     * Sets the tag ID of this tag.
     *
     * @param tagId the tag ID of this tag
     */
    public void setTagId(long tagId);

    /**
     * Returns the company ID of this tag.
     *
     * @return the company ID of this tag
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this tag.
     *
     * @param companyId the company ID of this tag
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this tag.
     *
     * @return the group ID of this tag
     */
    public long getGroupId();

    /**
     * Sets the group ID of this tag.
     *
     * @param groupId the group ID of this tag
     */
    public void setGroupId(long groupId);

    /**
     * Returns the tag no of this tag.
     *
     * @return the tag no of this tag
     */
    @AutoEscape
    public String getTagNo();

    /**
     * Sets the tag no of this tag.
     *
     * @param tagNo the tag no of this tag
     */
    public void setTagNo(String tagNo);

    /**
     * Returns the type of this tag.
     *
     * @return the type of this tag
     */
    public int getType();

    /**
     * Sets the type of this tag.
     *
     * @param type the type of this tag
     */
    public void setType(int type);

    /**
     * Returns the node ID of this tag.
     *
     * @return the node ID of this tag
     */
    public long getNodeId();

    /**
     * Sets the node ID of this tag.
     *
     * @param nodeId the node ID of this tag
     */
    public void setNodeId(long nodeId);

    /**
     * Returns the location ID of this tag.
     *
     * @return the location ID of this tag
     */
    public long getLocationId();

    /**
     * Sets the location ID of this tag.
     *
     * @param locationId the location ID of this tag
     */
    public void setLocationId(long locationId);

    /**
     * Returns the status of this tag.
     *
     * @return the status of this tag
     */
    public int getStatus();

    /**
     * Sets the status of this tag.
     *
     * @param status the status of this tag
     */
    public void setStatus(int status);

    /**
     * Returns the patient ID of this tag.
     *
     * @return the patient ID of this tag
     */
    public long getPatientId();

    /**
     * Sets the patient ID of this tag.
     *
     * @param patientId the patient ID of this tag
     */
    public void setPatientId(long patientId);

    /**
     * Returns the create date of this tag.
     *
     * @return the create date of this tag
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this tag.
     *
     * @param createDate the create date of this tag
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this tag.
     *
     * @return the modified date of this tag
     */
    public Date getModifiedDate();

    /**
     * Sets the modified date of this tag.
     *
     * @param modifiedDate the modified date of this tag
     */
    public void setModifiedDate(Date modifiedDate);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.Tag tag);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.Tag> toCacheModel();

    @Override
    public com.surwing.model.Tag toEscapedModel();

    @Override
    public com.surwing.model.Tag toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
