package com.surwing.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the UserInfo service. Represents a row in the &quot;M_UserInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.surwing.model.impl.UserInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.surwing.model.impl.UserInfoImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see UserInfo
 * @see com.surwing.model.impl.UserInfoImpl
 * @see com.surwing.model.impl.UserInfoModelImpl
 * @generated
 */
public interface UserInfoModel extends BaseModel<UserInfo> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a user info model instance should use the {@link UserInfo} interface instead.
     */

    /**
     * Returns the primary key of this user info.
     *
     * @return the primary key of this user info
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this user info.
     *
     * @param primaryKey the primary key of this user info
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the user ID of this user info.
     *
     * @return the user ID of this user info
     */
    public long getUserId();

    /**
     * Sets the user ID of this user info.
     *
     * @param userId the user ID of this user info
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this user info.
     *
     * @return the user uuid of this user info
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this user info.
     *
     * @param userUuid the user uuid of this user info
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the location ID of this user info.
     *
     * @return the location ID of this user info
     */
    public long getLocationId();

    /**
     * Sets the location ID of this user info.
     *
     * @param locationId the location ID of this user info
     */
    public void setLocationId(long locationId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.surwing.model.UserInfo userInfo);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.surwing.model.UserInfo> toCacheModel();

    @Override
    public com.surwing.model.UserInfo toEscapedModel();

    @Override
    public com.surwing.model.UserInfo toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
