package com.surwing.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.surwing.model.Bed;

import com.surwing.service.BedLocalServiceUtil;

/**
 * The extended model base implementation for the Bed service. Represents a row in the &quot;M_Bed&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BedImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see BedImpl
 * @see com.surwing.model.Bed
 * @generated
 */
public abstract class BedBaseImpl extends BedModelImpl implements Bed {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a bed model instance should use the {@link Bed} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            BedLocalServiceUtil.addBed(this);
        } else {
            BedLocalServiceUtil.updateBed(this);
        }
    }
}
