package com.surwing.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.surwing.model.SystemParameter;

import com.surwing.service.SystemParameterLocalServiceUtil;

/**
 * The extended model base implementation for the SystemParameter service. Represents a row in the &quot;M_SystemParameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SystemParameterImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see SystemParameterImpl
 * @see com.surwing.model.SystemParameter
 * @generated
 */
public abstract class SystemParameterBaseImpl extends SystemParameterModelImpl
    implements SystemParameter {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a system parameter model instance should use the {@link SystemParameter} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SystemParameterLocalServiceUtil.addSystemParameter(this);
        } else {
            SystemParameterLocalServiceUtil.updateSystemParameter(this);
        }
    }
}
