package com.surwing.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.surwing.model.Tag;

import com.surwing.service.TagLocalServiceUtil;

/**
 * The extended model base implementation for the Tag service. Represents a row in the &quot;M_Tag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TagImpl}.
 * </p>
 *
 * @author zhaiyz
 * @see TagImpl
 * @see com.surwing.model.Tag
 * @generated
 */
public abstract class TagBaseImpl extends TagModelImpl implements Tag {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a tag model instance should use the {@link Tag} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TagLocalServiceUtil.addTag(this);
        } else {
            TagLocalServiceUtil.updateTag(this);
        }
    }
}
