
package cn.com.winning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebService_BodyHeat", targetNamespace = "http://www.winning.com.cn/", wsdlLocation = "file:/home/zhaiyz/\u4e0b\u8f7d/WebServiceBodyHealt.wsdl")
public class WebServiceBodyHeat
    extends Service
{

    private final static URL WEBSERVICEBODYHEAT_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEBODYHEAT_EXCEPTION;
    private final static QName WEBSERVICEBODYHEAT_QNAME = new QName("http://www.winning.com.cn/", "WebService_BodyHeat");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/zhaiyz/\u4e0b\u8f7d/WebServiceBodyHealt.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEBODYHEAT_WSDL_LOCATION = url;
        WEBSERVICEBODYHEAT_EXCEPTION = e;
    }

    public WebServiceBodyHeat() {
        super(__getWsdlLocation(), WEBSERVICEBODYHEAT_QNAME);
    }

    public WebServiceBodyHeat(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEBODYHEAT_QNAME, features);
    }

    public WebServiceBodyHeat(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEBODYHEAT_QNAME);
    }

    public WebServiceBodyHeat(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEBODYHEAT_QNAME, features);
    }

    public WebServiceBodyHeat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceBodyHeat(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceBodyHeatPortType
     */
    @WebEndpoint(name = "WebService_BodyHeatPort")
    public WebServiceBodyHeatPortType getWebServiceBodyHeatPort() {
        return super.getPort(new QName("http://www.winning.com.cn/", "WebService_BodyHeatPort"), WebServiceBodyHeatPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceBodyHeatPortType
     */
    @WebEndpoint(name = "WebService_BodyHeatPort")
    public WebServiceBodyHeatPortType getWebServiceBodyHeatPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.winning.com.cn/", "WebService_BodyHeatPort"), WebServiceBodyHeatPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEBODYHEAT_EXCEPTION!= null) {
            throw WEBSERVICEBODYHEAT_EXCEPTION;
        }
        return WEBSERVICEBODYHEAT_WSDL_LOCATION;
    }

}
